[=] just refactor and instructions

diff --git a/mongodb b/mongodb
--- a/mongodb
+++ b/mongodb
@@ -1,12 +1,6 @@
-# -*- mode: sh; sh-basic-offset: 3; indent-tabs-mode: nil; -*-
-#
-# mongodb handler script for backupninja
-#
-
 getconf tar /bin/tar
 getconf mongodump /usr/bin/mongodump
 getconf backupdir /var/backups/mongodb
-getconf dumpopts ""
 getconf dbhost localhost
 getconf dbport 27017
 getconf mongouser
@@ -20,20 +14,20 @@ getconf vsname
 local usevserver=no
 local vroot
 if [ $vservers_are_available = yes ]; then
-   if [ -n "$vsname" ]; then
-      # does it exist ?
-      if ! vservers_exist "$vsname" ; then
-         fatal "The vserver given in vsname ($vsname) does not exist."
-      fi
-      # is it running ?
-      vservers_running $vsname || fatal "The vserver $vsname is not running."
-      # everything ok
-      info "Using vserver '$vsname'."
-      usevserver=yes
-      vroot="$VROOTDIR/$vsname"
-   else
-      info "No vserver name specified, actions will be performed on the host."
-   fi
+	if [ -n "$vsname" ]; then
+		# does it exist ?
+		if ! vservers_exist "$vsname" ; then
+			fatal "The vserver given in vsname ($vsname) does not exist."
+		fi
+		# is it running ?
+		vservers_running $vsname || fatal "The vserver $vsname is not running."
+		# everything ok
+		info "Using vserver '$vsname'."
+		usevserver=yes
+		vroot="$VROOTDIR/$vsname"
+	else
+		info "No vserver name specified, actions will be performed on the host."
+	fi
 fi
 
 
@@ -46,7 +40,7 @@ fi
 ## dumping mongodb
 
 if [ ! -f $vroot$mongodump ]; then
-        fatal "$vroot$mongodump does not exists"
+	fatal "$vroot$mongodump does not exists"
 fi
 
 if [ "$mongouser" -a "$mongopass" ]
@@ -67,62 +61,59 @@ then
 	COLLECTION="-c $mongocollection"
 fi
 
-if [ -n "$dumpopts" ]; then
-    EXTRA_OPTIONS="$dumpopts"
-fi
 
 if [ $usevserver = yes ]
 then
-        info "dbhost: $dbhost, dbport: $dbport"
+	info "dbhost: $dbhost, dbport: $dbport"
 
-        if [ ! -d $vroot$backupdir ]; then
-                fatal "$vroot$backupdir does not exists"
-        fi
+	if [ ! -d $vroot$backupdir ]; then
+		fatal "$vroot$backupdir does not exists"
+	fi
 
-        if [ ! -w $vroot$backupdir ]; then
-                fatal "$vroot$backupdir is not writable"
-        fi
+	if [ ! -w $vroot$backupdir ]; then
+		fatal "$vroot$backupdir is not writable"
+	fi
 
-        execdump="$VSERVER $vsname exec $mongodump -h $dbhost:$dbport -o $backupdir $AUTH $EXTRA_OPTIONS $DB $COLLECTION"
-        execrm="$VSERVER $vsname exec rm -rf $backupdir/*"
-else
-        if [ ! -d $backupdir ]; then
-                fatal "$backupdir does not exists"
-        fi
+	execdump="$VSERVER $vsname exec $mongodump -h $dbhost:$dbport -o $backupdir $AUTH $DB $COLLECTION"
+	execrm="$VSERVER $vsname exec rm -rf $backupdir/*"
+	else
+	if [ ! -d $backupdir ]; then
+		fatal "$backupdir does not exists"
+	fi
 
-        if [ ! -w $backupdir ]; then
-                fatal "$backupdir is not writable"
-        fi
+	if [ ! -w $backupdir ]; then
+		fatal "$backupdir is not writable"
+	fi
 
-        execdump="$mongodump -h $dbhost:$dbport -o $backupdir $AUTH $EXTRA_OPTIONS $DB $COLLECTION"
-        execrm="rm -rf $backupdir/*"
+	execdump="$mongodump -h $dbhost:$dbport -o $backupdir $AUTH $DB $COLLECTION"
+	execrm="rm -rf $backupdir/*"
 fi
 
 if [ ! $test ]; then
-        outputrm=`su $user -c "$execrm" 2>&1`
-        coderm=$?
+	outputrm=`su $user -c "$execrm" 2>&1`
+	coderm=$?
 
-        if [ "$coderm" == "0" ]; then
-                debug $outputrm
-                info "Successfully removed old dump (if exist)"
-        else
-                warning $outputrm
-                warning "Failed to remove old dump"
-        fi
+	if [ "$coderm" == "0" ]; then
+		debug $outputrm
+		info "Successfully removed old dump (if exist)"
+	else
+		warning $outputrm
+		warning "Failed to remove old dump"
+	fi
 
 
-        outputdump=`su $user -c "$execdump" 2>&1`
-        codedump=$?
+	outputdump=`su $user -c "$execdump" 2>&1`
+	codedump=$?
 
-        if [ "$codedump" == "0" ]; then
-                debug $outputdump
-                info "Successfully finished dump of all mongodb databases"
-        else
-                fatal $outputdump
-                fatal "Failed to dumping of mongodb databases"
-        fi
+	if [ "$codedump" == "0" ]; then
+		debug $outputdump
+		info "Successfully finished dump of all mongodb databases"
+	else
+		fatal $outputdump
+		fatal "Failed to dumping of mongodb databases"
+	fi
 else
-        debug "Running backup of mongodb"
+	debug "Running backup of mongodb"
 fi
 
 return 0
